# Import Python libraries

In [1]:
import xlwings as xw
import pandas as pd
import numpy as np
from poes.model.utils import param_poes
from poes.model.poes import poes

In [2]:
xb = xw.Book('poes/controller/control.xlsm')

In [3]:
sheet = xb.sheets['Resumen']

In [4]:
df_poes = sheet['A2'].options(pd.DataFrame, index=False, expand='table').value
df_poes

Variables  Data values         Dist.    Loc  Scale   Sc  Lim. Min.  \
0     Area        340.00    Triangular  400.0  600.0  0.3       50.0   
1   Espesor        40.00    Triangular    0.0   90.0  0.3        0.0   
2  Porosida         0.16    Log Normal    0.0    0.2  0.8        0.0   
3       Swi         0.51        Normal    0.4    0.2  NaN        0.0   
4       Boi         2.60  Exponencial     1.0    0.2  NaN        1.0   

   Lim. Max.  
0        NaN  
1      180.0  
2        0.4  
3        1.0  
4        2.0

# Exploratory data analysis

In [5]:
df_poes.columns

Index(['Variables', 'Data values', 'Dist.', 'Loc', 'Scale', 'Sc', 'Lim. Min.',
       'Lim. Max.'],
      dtype='object')

In [6]:
df_poes.columns = df_poes.columns.str.strip()

In [7]:
df_poes.columns

Index(['Variables', 'Data values', 'Dist.', 'Loc', 'Scale', 'Sc', 'Lim. Min.',
       'Lim. Max.'],
      dtype='object')

In [8]:
df_poes['Dist.'] = ['Triangular', 'Triangular', 'Log Normal', 'Normal', 'Exponencial']
df_poes

Variables  Data values        Dist.    Loc  Scale   Sc  Lim. Min.  Lim. Max.
0     Area        340.00   Triangular  400.0  600.0  0.3       50.0        NaN
1   Espesor        40.00   Triangular    0.0   90.0  0.3        0.0      180.0
2  Porosida         0.16   Log Normal    0.0    0.2  0.8        0.0        0.4
3       Swi         0.51       Normal    0.4    0.2  NaN        0.0        1.0
4       Boi         2.60  Exponencial    1.0    0.2  NaN        1.0        2.0

In [9]:
df_poes.shape

(5, 8)

In [10]:
df_poes['Loc'] = np.array([400, 0, 0, 0.4, 1])
df_poes['Scale'] = np.array([600, 90, 0.2, 0.2, 0.2])
df_poes['Sc'] = np.array([0.3, 0.3, 0.8, 0, 0.7])
df_poes['Lim. Min.'] = np.array([50, 0, 0, 0, 1])
df_poes['Lim. Max.'] = np.array([0, 180, 0.4, 1, 2])
df_poes

Variables  Data values        Dist.    Loc  Scale   Sc  Lim. Min.  Lim. Max.
0     Area        340.00   Triangular  400.0  600.0  0.3         50        0.0
1   Espesor        40.00   Triangular    0.0   90.0  0.3          0      180.0
2  Porosida         0.16   Log Normal    0.0    0.2  0.8          0        0.4
3       Swi         0.51       Normal    0.4    0.2  0.0          0        1.0
4       Boi         2.60  Exponencial    1.0    0.2  0.7          1        2.0

# Use Loc method from pandas to extract specific values

In [11]:
df_poes.loc[2, "Data values"]

0.16

In [12]:
df_poes.loc[3, "Variables"]

'Swi'

# Call param_poes function

In [13]:
df_poes.columns

Index(['Variables', 'Data values', 'Dist.', 'Loc', 'Scale', 'Sc', 'Lim. Min.',
       'Lim. Max.'],
      dtype='object')

In [14]:
df_poes

Variables  Data values        Dist.    Loc  Scale   Sc  Lim. Min.  Lim. Max.
0     Area        340.00   Triangular  400.0  600.0  0.3         50        0.0
1   Espesor        40.00   Triangular    0.0   90.0  0.3          0      180.0
2  Porosida         0.16   Log Normal    0.0    0.2  0.8          0        0.4
3       Swi         0.51       Normal    0.4    0.2  0.0          0        1.0
4       Boi         2.60  Exponencial    1.0    0.2  0.7          1        2.0

In [15]:
param_poes(df_poes, 1, 'Dist.', 'Loc', 'Scale', 1000, 'Sc', 'Lim. Min.', 'Lim. Max.')

array([79.3096987 , 20.85707825, 81.24533163, 29.29435063, 56.22062052,
       52.49239542, 26.04578414, 16.82478246, 57.08520781, 54.27608484,
       71.87542975, 30.36402618, 33.05639392, 59.97690703, 42.78781823,
       18.51975575, 10.16503661, 27.29909288, 51.13485582,  3.67285565,
       16.40857209, 38.94173928, 33.60093449, 16.84084053, 34.91064123,
       31.83790528, 45.27940969, 24.7526273 , 41.47784724, 20.49016011,
       29.05086236, 29.88242758, 44.11194185, 36.51255112, 54.70251688,
       72.13144091,  5.8024732 , 79.14702591, 35.66555047, 18.49220572,
        4.54821868, 63.40218484, 68.04198705, 50.18995981, 21.74347027,
       20.71123251, 25.30295301, 76.87483012,  9.95102517, 24.24212644,
       39.74265405,  8.3589435 , 41.24143604, 30.00922772, 13.1257314 ,
        6.55426452, 31.19304232, 64.07110309,  7.28485996,  7.01798224,
       52.34385168, 24.09220144, 77.61547957, 29.25911898, 57.57604397,
       32.75014694, 37.21589184, 19.20596701, 54.22554269,  5.79

In [16]:
param_poes(df_poes, 4, 'Dist.', 'Loc', 'Scale', 1000, 'Sc', 'Lim. Min.', 'Lim. Max.')

array([1.14912308, 1.18409626, 1.14214694, 1.26107252, 2.        ,
       1.28668217, 1.19603808, 1.28289948, 1.09964076, 1.29998918,
       1.19030656, 1.07574426, 1.16659625, 1.01427615, 1.05202254,
       1.603543  , 1.02973843, 1.23086097, 1.10348808, 1.008664  ,
       1.28405721, 1.00533958, 1.73260499, 1.12544007, 1.0201678 ,
       1.09647954, 1.05093031, 1.13824695, 1.13720155, 1.39504028,
       1.11913129, 1.09257714, 1.15106316, 1.83027694, 1.25936652,
       1.06869752, 1.06436985, 1.06213428, 1.00402577, 1.133614  ,
       1.39552229, 1.70014561, 1.12761639, 1.12295098, 1.24980828,
       1.05518959, 1.48770315, 1.19846579, 1.16364155, 1.07445319,
       1.12079412, 1.06979043, 1.03548049, 1.25451436, 1.27774834,
       1.06272848, 1.25642891, 1.03529732, 1.01276426, 1.53550831,
       1.54048448, 1.10930534, 1.03892467, 1.07962499, 1.1082306 ,
       1.02263313, 1.368514  , 1.36705318, 1.29955978, 1.06962475,
       1.04404386, 1.31982204, 1.10153646, 1.47632172, 1.11074

# Exploring codes from control file

In [17]:
input_col_names = df_poes["Variables"].to_list()
area_col, h_col, poro_col, sw_col, boi_col = tuple(input_col_names)
input_idx = [0, 1, 2, 3, 4]
input_dict = dict(zip(input_col_names, input_idx))
results_dict = {}
h_col

'Espesor'

In [18]:
input_col_names

['Area ', 'Espesor', 'Porosida', 'Swi', 'Boi']

In [19]:
input_dict

{'Area ': 0, 'Espesor': 1, 'Porosida': 2, 'Swi': 3, 'Boi': 4}

In [20]:
for col, idx in input_dict.items():
    results_dict[col] = param_poes(
        df_poes, idx, 'Dist.', 'Loc', 'Scale', 100, 'Sc', 'Lim. Min.', 'Lim. Max.'
    )

In [21]:
  results_dict["poes_prob"] = poes(
        results_dict[area_col],
        results_dict[h_col],
        results_dict[poro_col],
        results_dict[sw_col],
        results_dict[boi_col],
     )

In [22]:
results_dict['poes_prob']

array([35164185.39360553, 23365759.97725288, 13816115.11945734,
       10808012.98274636, 31667258.43755761, 41322121.73981928,
       18513088.0461221 ,  3055539.33660229, 26926594.31641935,
       24895516.12257381, 23544264.13997891, 32087698.2558464 ,
       72704901.50131251, 19691583.10237765, 28776948.95361716,
        9641467.14976664, 61228490.12950263, 18352131.1593984 ,
       73393003.84284692, 34820274.81896595,  8646936.496107  ,
       16826413.45521969, 75657597.47433348, 11303748.36174011,
       16630306.82387384,  4012826.45935444, 26942035.17930211,
       47685914.57246277, 10159853.97125196, 30724689.72960655,
       14186245.40678414, 27717097.18497211,   586783.01719707,
        6199480.00426261, 27710623.44437254, 10088144.24789938,
        3755474.97496411,  6711919.61524295, 22616467.39870485,
       23165677.49414456, 25841575.49594475, 42395158.41881085,
       34904522.00637148, 18004541.35501878, 11866383.47551841,
       28866225.26983199, 28000751.15999

In [23]:
df_prob = pd.DataFrame(results_dict)
df_prob

Area     Espesor  Porosida       Swi       Boi     poes_prob
0   634.725562  42.236219  0.318992  0.290348  1.338890  3.516419e+07
1   667.941546  37.347852  0.318532  0.566183  1.144547  2.336576e+07
2   786.876073  24.899748  0.114353  0.175642  1.037117  1.381612e+07
3   638.629626  23.847030  0.108194  0.083017  1.084553  1.080801e+07
4   752.114620  45.614449  0.231275  0.273890  1.411419  3.166726e+07
..         ...        ...       ...       ...       ...           ...
95  449.168124  67.904095  0.120528  0.291247  1.449985  1.394040e+07
96  875.646209  26.596473  0.400000  0.269427  1.244836  4.241443e+07
97  646.669045  17.660222  0.223134  0.121641  1.042117  1.666282e+07
98  580.143922   2.726689  0.400000  0.411235  2.000000  1.445085e+06
99  552.717854  27.032247  0.233999  0.265008  1.017089  1.960078e+07

[100 rows x 6 columns]

In [28]:
stoiip_summary_results = [
        results_dict["poes_prob"].mean(),
        results_dict["poes_prob"].std(),
        np.percentile(results_dict["poes_prob"], 10),
        np.percentile(results_dict["poes_prob"], 50),
        np.percentile(results_dict["poes_prob"], 90),
     ]

In [29]:
stoiip_summary_results

[23669927.40257779,
 20164946.645713784,
 4438951.28147963,
 19056935.297943436,
 48387284.95106041]