# Import Python libraries

In [39]:
import xlwings as xw
import pandas as pd
import numpy as np
from poes.model.utils import param_poes
from poes.model.poes import poes

In [40]:
xb = xw.Book('poes/controller/control.xlsm')

In [41]:
sheet = xb.sheets['Resumen']

In [42]:
df_poes = sheet['A2'].options(pd.DataFrame, index=False, expand='table').value
df_poes

Variables  Data values         Dist.    Loc  Scale   Sc  Lim. Min.  \
0     Area        340.00    Triangular  400.0  600.0  0.3       50.0   
1   Espesor        40.00    Triangular    0.0   90.0  0.3        0.0   
2  Porosida         0.16    Log Normal    0.0    0.2  0.8        0.0   
3       Swi         0.51        Normal    0.4    0.2  NaN        0.0   
4       Boi         2.60  Exponencial     1.0    0.2  NaN        1.0   

   Lim. Max.  
0        NaN  
1      180.0  
2        0.4  
3        1.0  
4        2.0

# Exploratory data analysis

In [43]:
df_poes.columns

Index(['Variables', 'Data values', 'Dist.', 'Loc', 'Scale', 'Sc', 'Lim. Min.',
       'Lim. Max.'],
      dtype='object')

In [44]:
df_poes.columns = df_poes.columns.str.strip()

In [45]:
df_poes.columns

Index(['Variables', 'Data values', 'Dist.', 'Loc', 'Scale', 'Sc', 'Lim. Min.',
       'Lim. Max.'],
      dtype='object')

In [46]:
df_poes['Dist.'] = ['Triangular', 'Triangular', 'Log Normal', 'Normal', 'Exponencial']
df_poes

Variables  Data values        Dist.    Loc  Scale   Sc  Lim. Min.  Lim. Max.
0     Area        340.00   Triangular  400.0  600.0  0.3       50.0        NaN
1   Espesor        40.00   Triangular    0.0   90.0  0.3        0.0      180.0
2  Porosida         0.16   Log Normal    0.0    0.2  0.8        0.0        0.4
3       Swi         0.51       Normal    0.4    0.2  NaN        0.0        1.0
4       Boi         2.60  Exponencial    1.0    0.2  NaN        1.0        2.0

In [47]:
df_poes.shape

(5, 8)

In [48]:
df_poes['Loc'] = np.array([400, 0, 0, 0.4, 1])
df_poes['Scale'] = np.array([600, 90, 0.2, 0.2, 0.2])
df_poes['Sc'] = np.array([0.3, 0.3, 0.8, 0, 0.7])
df_poes['Lim. Min.'] = np.array([50, 0, 0, 0, 1])
df_poes['Lim. Max.'] = np.array([0, 180, 0.4, 1, 2])
df_poes

Variables  Data values        Dist.    Loc  Scale   Sc  Lim. Min.  Lim. Max.
0     Area        340.00   Triangular  400.0  600.0  0.3         50        0.0
1   Espesor        40.00   Triangular    0.0   90.0  0.3          0      180.0
2  Porosida         0.16   Log Normal    0.0    0.2  0.8          0        0.4
3       Swi         0.51       Normal    0.4    0.2  0.0          0        1.0
4       Boi         2.60  Exponencial    1.0    0.2  0.7          1        2.0

# Use Loc method from pandas to extract specific values

In [49]:
df_poes.loc[2, "Data values"]

0.16

In [50]:
df_poes.loc[3, "Variables"]

'Swi'

# Call param_poes function

In [51]:
df_poes.columns

Index(['Variables', 'Data values', 'Dist.', 'Loc', 'Scale', 'Sc', 'Lim. Min.',
       'Lim. Max.'],
      dtype='object')

In [52]:
df_poes

Variables  Data values        Dist.    Loc  Scale   Sc  Lim. Min.  Lim. Max.
0     Area        340.00   Triangular  400.0  600.0  0.3         50        0.0
1   Espesor        40.00   Triangular    0.0   90.0  0.3          0      180.0
2  Porosida         0.16   Log Normal    0.0    0.2  0.8          0        0.4
3       Swi         0.51       Normal    0.4    0.2  0.0          0        1.0
4       Boi         2.60  Exponencial    1.0    0.2  0.7          1        2.0

In [53]:
param_poes(df_poes, 1, 'Dist.', 'Loc', 'Scale', 1000, 'Sc', 'Lim. Min.', 'Lim. Max.')

array([17.14993934, 34.11234318, 31.94393461,  5.96429589, 18.75263225,
       83.4527661 , 38.36653815, 45.65701916, 31.32685185, 31.91589247,
       51.97533953, 83.21787597, 47.87041015, 39.4660678 , 45.50048348,
       21.82899863, 35.44719085, 32.68083858, 35.37408698, 28.02617884,
       41.6059315 , 28.80052723, 28.43886444, 28.79853472, 60.37624162,
       24.84259584, 22.11504449, 51.07463796, 42.05474296, 61.97091169,
       31.59317958, 13.38970564, 31.73111539, 80.00014803, 50.03699348,
       65.80586106, 86.60664856, 59.74910739, 36.87923571, 73.71962623,
        7.04377502, 58.53135128, 64.49692263, 40.49127938, 70.66654164,
       19.62103312, 21.80867908, 53.73924123, 50.95236535, 12.89337544,
       32.67901185, 26.09750579, 24.45721668, 53.29272541, 70.21380817,
       61.97215942, 73.83106078,  7.93345731, 33.4210437 , 85.25861818,
       23.8767394 , 30.9915116 , 69.4041963 , 42.09038252, 49.65233709,
       67.9418673 , 38.84435954, 75.74880311, 65.44762611, 18.05

In [54]:
param_poes(df_poes, 4, 'Dist.', 'Loc', 'Scale', 1000, 'Sc', 'Lim. Min.', 'Lim. Max.')

array([1.42890821, 1.59980737, 1.10568111, 1.60901267, 1.21540476,
       1.01967038, 1.47214978, 1.21999956, 1.0051039 , 1.00203506,
       1.26007873, 1.05026348, 1.1879893 , 1.03018366, 1.24779093,
       1.1217734 , 1.06901425, 1.18120633, 1.21244122, 1.79747564,
       1.41683111, 1.06789514, 1.0427768 , 1.11354448, 1.07400409,
       1.10870976, 1.30278643, 1.19639026, 1.28958438, 1.38258366,
       1.09134953, 1.09480531, 1.0417256 , 1.0472884 , 1.06749376,
       1.13142324, 1.09550468, 1.15847792, 1.2720981 , 1.68373882,
       1.07174539, 1.01119208, 1.2492189 , 1.12783211, 1.39150684,
       1.11488029, 1.10311748, 1.14883554, 1.66635946, 1.28229411,
       1.12960827, 1.32572716, 1.23565258, 1.39325246, 1.54511753,
       1.42076658, 1.02395487, 1.01512954, 1.06619786, 1.29048726,
       1.22669979, 1.1162061 , 1.33553648, 1.03790972, 1.17141906,
       1.22025348, 1.14851925, 1.36939117, 1.0341739 , 1.09531522,
       1.01136495, 1.06143428, 1.1984193 , 1.52830705, 1.00486

# Exploring codes from control file

In [55]:
input_col_names = df_poes["Variables"].to_list()
area_col, h_col, poro_col, sw_col, boi_col = tuple(input_col_names)
input_idx = [0, 1, 2, 3, 4]
input_dict = dict(zip(input_col_names, input_idx))
results_dict = {}
h_col

'Espesor'

In [56]:
input_col_names

['Area ', 'Espesor', 'Porosida', 'Swi', 'Boi']

In [57]:
input_dict

{'Area ': 0, 'Espesor': 1, 'Porosida': 2, 'Swi': 3, 'Boi': 4}

In [58]:
for col, idx in input_dict.items():
    results_dict[col] = param_poes(
        df_poes, idx, 'Dist.', 'Loc', 'Scale', 100, 'Sc', 'Lim. Min.', 'Lim. Max.'
    )

In [59]:
  results_dict["poes_prob"] = poes(
        results_dict[area_col],
        results_dict[h_col],
        results_dict[poro_col],
        results_dict[sw_col],
        results_dict[boi_col],
     )

In [60]:
results_dict['poes_prob']

array([2.72473669e+07, 4.20857628e+07, 8.28887695e+05, 2.62888389e+07,
       1.13198704e+07, 3.81917844e+07, 1.49924437e+07, 8.12653332e+07,
       3.97681939e+06, 3.25835375e+07, 2.37488382e+06, 2.89043997e+06,
       4.21852592e+06, 1.25931738e+07, 1.25631744e+07, 1.04412858e+08,
       4.31316895e+07, 2.06408633e+06, 2.93736607e+07, 5.43735028e+06,
       1.26838059e+07, 1.59995881e+07, 4.27027502e+07, 6.24646465e+06,
       5.57556546e+06, 1.29868696e+07, 1.23099762e+07, 3.22590184e+06,
       2.52216526e+07, 5.08629420e+07, 5.16202565e+07, 4.37678112e+07,
       5.37148843e+07, 6.99140180e+07, 8.31425951e+06, 2.64478434e+07,
       4.44345481e+06, 2.20127043e+07, 1.77281886e+07, 2.63027508e+07,
       2.41301699e+07, 4.10070760e+07, 1.49237657e+07, 4.59216332e+07,
       9.13575652e+06, 3.46057067e+07, 7.57667403e+06, 1.66589994e+07,
       2.80026288e+07, 4.00417662e+07, 2.09501133e+07, 3.73250445e+07,
       1.65596063e+07, 4.56578288e+07, 5.06676466e+06, 1.55274740e+07,
      

In [62]:
df_prob = pd.DataFrame(results_dict)
df_prob

Area     Espesor  Porosida       Swi       Boi     poes_prob
0   802.613103  22.394966  0.352798  0.407400  1.069966  2.724737e+07
1   717.440655  38.147889  0.324388  0.374136  1.024275  4.208576e+07
2   541.245802  23.742404  0.157397  0.945019  1.040832  8.288877e+05
3   888.060947  14.105804  0.400000  0.167122  1.231573  2.628884e+07
4   613.941968  29.790272  0.163304  0.488771  1.046460  1.131987e+07
..         ...        ...       ...       ...       ...           ...
95  536.237774  61.502604  0.278609  0.285577  1.268881  4.013570e+07
96  613.441739  25.198216  0.400000  0.478638  1.678627  1.489835e+07
97  856.144484  23.013679  0.044117  0.083410  1.030085  6.000492e+06
98  785.784793  22.163067  0.157930  0.111146  1.151798  1.646656e+07
99  580.339598  60.372183  0.339539  0.611045  1.194381  3.005488e+07

[100 rows x 6 columns]

In [63]:
stoiip_summary_results = [
        results_dict["poes_prob"].mean(),
        results_dict["poes_prob"].std(),
        np.percentile(results_dict["poes_prob"], 10),
        np.percentile(results_dict["poes_prob"], 50),
        np.percentile(results_dict["poes_prob"], 90),
     ]
sheet[STOC_STOIIP_RESULTS].options(transpose=True).value

In [64]:
stoiip_summary_results

[21369507.21100173,
 19098525.353850953,
 2884020.431511688,
 16244065.134106152,
 44873333.82878016]